name: Build Release Mac Arm64
on: [push]
jobs:
    build:
        name: macos-14
        runs-on: macos-14
        permissions:
          contents: write
          packages: write

        steps:
          - name: Node
            uses: actions/setup-node@v4
            with:
              node-version: 18

          - name: 拉取自身仓库代码
            uses: actions/checkout@v4
            # with:
            #   ref: main

          - name: 安装依赖
            run: |
              yarn

          - name: 构建 ${{ runner.arch }}
            run: |
              yarn make
              yarn push:release
